# <center>Pandas Series</center>

* [<span style='color:purple'>Series Properties](#Series-Properties)
* [<span style='color:purple'>Pandas Datatype and Type conversion](#Pandas-Datatype-and-Type-conversion)
 

Series are pandas data structure built on top of NumPy arrays.
* Series also contain an index and an optional name,in addition to array of data.
* Two or more series can grouped together form a Pandas DataFrame.

In [11]:
import numpy as np
import pandas as pd


In [12]:
sales =[10,29,30,40,76,54,34,56,78,90,100]

sales_series =pd.Series(sales)

In [13]:
sales_series

0      10
1      29
2      30
3      40
4      76
5      54
6      34
7      56
8      78
9      90
10    100
dtype: int64

## Series Properties

Pandas series have these key properties:
* Values - the data array in the series.
* index - the index array in the series.
* name - the optional name for the series.
* dtype - the data type of element in the value array.

In [14]:
sales_series.values

array([ 10,  29,  30,  40,  76,  54,  34,  56,  78,  90, 100], dtype=int64)

In [15]:
sales_series.index

RangeIndex(start=0, stop=11, step=1)

In [16]:
sales_series

0      10
1      29
2      30
3      40
4      76
5      54
6      34
7      56
8      78
9      90
10    100
dtype: int64

In [17]:
sales_series.dtype

dtype('int64')

In [22]:
number_series = pd.Series(range(10,100,5),name='number')

In [23]:
number_series

0     10
1     15
2     20
3     25
4     30
5     35
6     40
7     45
8     50
9     55
10    60
11    65
12    70
13    75
14    80
15    85
16    90
17    95
Name: number, dtype: int64

In [24]:
number_series.name

'number'

In [25]:
number_series.dtype

dtype('int64')

In [26]:
number_series.values

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95], dtype=int64)

## Pandas Datatype and Type conversion

Pandas datatype mostly expand on the base python and numpy.
* boolean - Nullable Boolean true/false.
* int64 - Nullable whole numbers.
* float64 -Nullable decimal numbers.
* String -Only contain strings or text.
* Category -maps categorical data to numeric array.


In [28]:
#you can convert data type in a pandas series by using .astype() method
number_series.astype("float")

0     10.0
1     15.0
2     20.0
3     25.0
4     30.0
5     35.0
6     40.0
7     45.0
8     50.0
9     55.0
10    60.0
11    65.0
12    70.0
13    75.0
14    80.0
15    85.0
16    90.0
17    95.0
Name: number, dtype: float64

# Assignment 1: Series Basics
 

* Convert `oil_array` into a Pandas Series, called `oil_series`. Give it a name!
* Return the name, dtype, size, and index of `oil_series`.

Take the mean of the values array. 

Then, convert the series to integer datatype and recalculate the mean. 


In [30]:
# create a DataFrame from the oil file, drop missing values
oil = pd.read_csv("oil.csv").dropna()

In [31]:
oil

,date,dcoilwtico
1,2013-01-02,93.14
2,2013-01-03,92.97
3,2013-01-04,93.12
4,2013-01-07,93.20
5,2013-01-08,93.21
...,...,...
1213,2017-08-25,47.65
1214,2017-08-28,46.40
1215,2017-08-29,46.46
1216,2017-08-30,45.96


In [32]:
oil_array = np.array(oil["dcoilwtico"].iloc[1000:1100])

In [33]:
oil_array

array([52.22, 51.44, 51.98, 52.01, 52.82, 54.01, 53.8 , 53.75, 52.36,
       53.26, 53.77, 53.98, 51.95, 50.82, 52.19, 53.01, 52.36, 52.45,
       51.12, 51.39, 52.33, 52.77, 52.38, 52.14, 53.24, 53.18, 52.63,
       52.75, 53.9 , 53.55, 53.81, 53.01, 52.19, 52.37, 52.99, 53.84,
       52.96, 53.21, 53.11, 53.41, 53.41, 54.02, 53.61, 54.48, 53.99,
       54.04, 54.  , 53.82, 52.63, 53.33, 53.19, 52.68, 49.83, 48.75,
       48.05, 47.95, 47.24, 48.34, 48.3 , 48.34, 47.79, 47.02, 47.29,
       47.  , 47.3 , 47.02, 48.36, 49.47, 50.3 , 50.54, 50.25, 50.99,
       51.14, 51.69, 52.25, 53.06, 53.38, 53.12, 53.19, 52.62, 52.46,
       50.49, 50.26, 49.64, 48.9 , 49.22, 49.22, 48.96, 49.31, 48.83,
       47.65, 47.79, 45.55, 46.23, 46.46, 45.84, 47.28, 47.81, 47.83,
       48.86])

In [34]:
oil_series =pd.Series(oil_array,name="oil price")

In [35]:
oil_series

0     52.22
1     51.44
2     51.98
3     52.01
4     52.82
      ...  
95    45.84
96    47.28
97    47.81
98    47.83
99    48.86
Name: oil price, Length: 100, dtype: float64

In [40]:
print("name of sereis --",oil_series.name)
print("datatype of series --",oil_series.dtype)
print("size od series--",oil_series.size)
print("index of series--",oil_series.index)

name of sereis -- oil price
datatype of series -- float64
size od series-- 100
index of series-- RangeIndex(start=0, stop=100, step=1)


In [41]:
print("mean --",oil_series.values.mean())

mean -- 51.128299999999996
